# Generated by Django 3.1.3 on 2020-12-25 22:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=200)),
                ('capacity', models.CharField(default='', max_length=20)),
                ('equipment', models.CharField(max_length=200)),
                ('mileage', models.CharField(max_length=8)),
                ('price', models.CharField(max_length=20)),
                ('available', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('phone_number_ad', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(12)])),
                ('author_ad', models.CharField(default='', max_length=20)),
                ('image', models.ImageField(null=True, upload_to='img')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='brands.brand')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year', to='brands.year')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ('-created_at',),
            },
        ),
    ]
